[generic]

number_of_emergency_streams = 1


[random ET values]
# these values are only used when creating completely randomized ET streams

min_bucket_size_byte = 3000
max_bucket_size_byte = 10000
step_bucket_size_byte = 1000

# values must be greater than 64
frame_sizes_in_byte = [100]

min_inter_event_time_us = [200, 400]
