name: eval_wired_sporadic_MKFirm
channels:
  - defaults
  - conda-forge
  - ibmdecisionoptimization
dependencies:
  - python=3.12
  - networkx=3.1
  - lxml
  - pygraphviz=1.9
  - numpy[version='>=1.26,<2.0']
  - matplotlib[version='>=3.8,<4.0']
  - ibmdecisionoptimization::docplex
  - conda-forge::graph-tool
  - natsort
  - pandas
