[generic]

# set by script:
# number_of_tt_streams = 2

# this denotes the portion of TT streams, that are to be marked as ET capable, i.e., the ET creator can use these streams
# as template for the ET streams
ET_capable_portion = 0.7

# qol parameter, when combining multiple scenarios, this can be used to have continuous ids
first_stream_id = 0

frame_sizes_in_byte = [100]
periods_in_us = [200]


# 0: absolutely no slack time. Frame needs to be sent at release and cannot be delayed
# i.e., deadline is release time + min end-to-end delay
# 1: deadline is release time + period
max_delay_percentage = [0.75]
