[generic]

number_of_emergency_streams = 5


[random ET values]
# these values are only used when creating completely randomized ET streams

min_bucket_size_byte = 3000
max_bucket_size_byte = 10000
step_bucket_size_byte = 1000

frame_sizes_in_byte = [100]
survival_times_us = [500, 1000]
