[generic]

number_of_tt_streams = 10

min_frame_size_byte = 64
max_frame_size_byte = 1500

periods_in_us = [100, 200, 300, 400]

# 0: absolutely no slack time. Frame needs to be sent at release and cannot be delayed
# i.e., deadline is release time + min end-to-end delay
# 1: deadline is release time + period
max_delay_percentage = [0.5, 0.75, 1]

